name: Robot Framework CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Robot Tests
      run: |
        robot tests/

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: |
          report.html
          log.html
          output.xml